# Generated by Django 4.2.25 on 2025-10-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmodel',
            table='test_model',
        ),
    ]
