# Generated by Django 4.2.25 on 2025-10-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_testmodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
